# Author: SumitModak <sumit.modak.code@gmail.com>

"ui.background" = { bg = "base00" }
"ui.gutter" = { bg = "base00" }
"ui.virtual.whitespace" = "base03"
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.linenr" = { fg = "base03", bg = "base00" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr.selected" = { fg = "base05", bg = "base00", modifiers = ["bold"] }
"ui.selection" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"ui.text" = "base05"
"ui.text.focus" = "base05"
"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base06", bg = "base01" }
"ui.help" = { fg = "base06", bg = "base01" }

"comment" = "base03"
"operator" = "base05"
"constant" = "base09"
"constant.builtin" = "base09"
"constant.numeric" = "base09"
"constant.character.escape" = "base0C"
"keyword" = "base0E"
"namespace" = "base0E"
"type.builtin" = "base0E"
"type" = "base0A"
"attribute" = "base09"
"variable" = "base08"
"variable.builtin" = "base08"
"variable.other.member" = "base0B"
"string" = "base0B"
"function" = "base0D"
"constructor" = "base0D"
"special" = "base0D"
"label" = "base0E"

"markup.heading" = "base0D"
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0B"
"diff.delta" = "base09"
"diff.minus" = "base08"

"diagnostic" = { modifiers = ["underlined"] }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base09"
"error" = "base08"

[palette]
base00 = "#080808" # Default Background
base01 = "#181818" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#383838" # Selection Background
base03 = "#585858" # Comments, Invisibles, Line Highlighting
base04 = "#b8b8b8" # Dark Foreground (Used for status bars)
base05 = "#d8d8d8" # Default Foreground, Caret, Delimiters, Operators
base06 = "#e8e8e8" # Light Foreground (Not often used)
base07 = "#f8f8f8" # Light Background (Not often used)
base08 = "#ab4642" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted    # light red
base09 = "#dc9656" # Integers, Boolean, Constants, XML Attributes, Markup Link Url        # yellowish-orange
base0A = "#f7ca88" # Classes, Markup Bold, Search Text Background                         # light yellowish-orange
base0B = "#a1b56c" # Strings, Inherited Class, Markup Code, Diff Inserted                 # light green
base0C = "#86c1b9" # Support, Regular Expressions, Escape Characters, Markup Quotes       # light cyan
base0D = "#7cafc2" # Functions, Methods, Attribute IDs, Headings                          # light blue
base0E = "#ba8baf" # Keywords, Storage, Selector, Markup Italic, Diff Changed             # light magenta

base0F = "#a16946" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>    # dull orange
base10 = "#df9f4f" #                                                                      # orange
base11 = "#4fc1ff" #                                                                      # blue
base12 = "#9cdcfe" #                                                                      # bright blue
base13 = "#264f78" #                                                                      # light brown

base14 = "#86c1b9" #                                                                      # light cyan
base15 = "#7cafc2" #                                                                      # light blue
base16 = "#ba8baf" #                                                                      # light magenta
base17 = "#a16946" #                                                                      # dull orange
