# Author: SumitModak <sumit.modak.code@gmail.com>

"ui.background" = { bg = "base00" }
"ui.gutter" = { bg = "base00" }
"ui.virtual.whitespace" = "base03"
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.linenr" = { fg = "base03", bg = "base00" }
"ui.popup" = { bg = "base01" }
"ui.window" = { bg = "base01" }
"ui.linenr.selected" = { fg = "base05", bg = "base00", modifiers = ["bold"] }
"ui.selection" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.cursor" = { fg = "base04", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "base05", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "base0A", modifiers = ["underlined"] }
"ui.text" = "base05"
"ui.text.focus" = "base05"
"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.bufferline.active" = { fg = "base06", bg = "base01" }
"ui.help" = { fg = "base06", bg = "base01" }

"operator" = "base05"
"comment" = "base03"
"comment.block.documentation" = "base0F"
"string" = "base0B"
"constant" = "base09"
"constant.builtin" = "base09"
"constant.numeric" = "base09"
"constant.character.escape" = "base0C"
"keyword" = "base10"
"type.builtin" = "base10"
"type" = "base0A"
"type.enum.variant" = "base0B"
"variable.other.member" = "base0B"
"variable" = "base08"
"variable.builtin" = "base08"
"function" = "base0D"
"constructor" = "base0D"
"function.macro" = "base0E"
"keyword.directive" = "base0E"
"namespace" = "base11"
"tag" = "base08"
"attribute" = "base09"
"special" = "base0D"
"label" = "base10"

"markup.heading" = "base0D"
"markup.list" = "base08"
"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.italic" = { fg = "base10", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.link.text" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"

"diff.plus" = "base0B"
"diff.delta" = "base09"
"diff.minus" = "base08"

"diagnostic" = { modifiers = ["underlined"] }
"info" = "base0D"
"hint" = "base03"
"debug" = "base03"
"warning" = "base09"
"error" = "base08"

[palette]
base00 = "#080808" # Default Background
base01 = "#181818" # Lighter Background (Used for status bars, line number and folding marks)
base02 = "#383838" # Selection Background
base03 = "#585858" # Comments, Invisibles, Line Highlighting
base04 = "#b8b8b8" # Dark Foreground (Used for status bars)
base05 = "#d8d8d8" # Default Foreground, Caret, Delimiters, Operators
base06 = "#e8e8e8" # Light Foreground (Not often used)
base07 = "#f8f8f8" # Light Background (Not often used)

base08 = "#ab4642" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted    # dark red
base09 = "#dc9656" # Constants, XML Attributes, Markup Link Url, Diff Modified            # dark orange
base0A = "#edc677" # Classes, Markup Bold, Search Text Background                         # light yellow
base0B = "#a1b56c" # Strings, Type Members, Inherited Class, Markup Code, Diff Inserted   # dark green

base0C = "#8fc7bf" # Support, Escape Characters, Markup Quotes                            # light cyan
base0D = "#75b7c7" # Functions, Methods, Attribute IDs, Headings                          # light blue
base0E = "#57afd7" # Macros, Preprocessor Directives                                      # deep blue
base0F = "#8b9eb7" # Documentation Comment                                                # grayish-blue

base10 = "#ba8baf" # Keywords, Storage, Selector, Markup Italic, Diff Changed             # light magenta
base11 = "#a576a0" # Namespaces                                                           # dark magenta
