theme = "dark_plus_mdf"
# "snazzy" "heisenberg" "mellow" "github_dark" "onedarker" "ayu_dark" "onedark"

[editor]
bufferline = "always"
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "hidden"

[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding"]

[keys.normal]
# commands
q = ":w"
Q = ":q!"
C-f = [":new", ":insert-output ~/.config/lf/lf-pick", ":theme default", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme dark_plus_mdf"]
# movement
w = "move_visual_line_up"
a = "move_char_left"
r = "move_visual_line_down"
s = "move_char_right"
W = "half_page_up"
A = "goto_line_start"
R = "half_page_down"
S = "goto_line_end"
m = "move_prev_word_start"
M = "move_prev_long_word_start"
n = "move_next_word_start"
N = "move_next_long_word_start"
e	= "move_next_word_end"
E = "move_next_long_word_end"
# changes
c = "yank"
C = "change_selection"
p = "paste_before"
P = "paste_after"
x = "delete_selection"
d = "delete_selection_noyank"
u = "undo"
U = "redo"
# search
f = "search"
F = "rsearch"
"\\" = "search_next"
"|" = "search_prev"
t = "find_next_char"
T = "find_prev_char"
