# theme = "my_dark_plus"
theme = "my_base16_dark"

# theme = "adwaita-dark"
# theme = "amberwood"
# theme = "autumn"
# theme = "autumn_night"
# theme = "ayu_dark"
# theme = "ayu_evolve"
# theme = "catppuccin_frappe"
# theme = "catppuccin_macchiato"
# theme = "catppuccin_mocha"
# theme = "darcula-solid"
# theme = "darcula"
# theme = "dracula_at_night"
# theme = "everblush"
# theme = "fleet_dark"
# theme = "github_dark"
# theme = "github_dark_colorblind"
# theme = "github_dark_dimmed"
# theme = "github_dark_high_contrast"
# theme = "github_dark_tritanopia"
# theme = "gruvbox"
# theme = "gruvbox_dark_hard"
# theme = "jellybeans"
# theme = "kanagawa"
# theme = "kaolin-valley-dark"
# theme = "material_darker"
# theme = "material_deep_ocean"
# theme = "mellow"
# theme = "molokai"
# theme = "monokai"
# theme = "monokai_aqua"
# theme = "monokai_pro"
# theme = "monokai_pro_machine"
# theme = "monokai_pro_octagon"
# theme = "monokai_pro_ristretto"
# theme = "monokai_pro_spectrum"
# theme = "new_moon"
# theme = "nightfox"
# theme = "nord-night"
# theme = "nord"
# theme = "onedark"
# theme = "papercolor-dark"
# theme = "penumbra+"
# theme = "pop-dark"
# theme = "rasmus"
# theme = "snazzy"
# theme = "solarized_dark"
# theme = "sonokai"
# theme = "tokyonight"
# theme = "varua"
# theme = "vim_dark_high_contrast"
# theme = "zed_onedark"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "hidden"
  
[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding"]

[editor.lsp]
enable = true

[keys.normal]
q = ":buffer-close"
Q = ":buffer-close!"
z = ":write"
Z = ":write!"
h = [ "collapse_selection", "insert_mode" ]
n = [ "move_char_right", "insert_mode" ]
s = "select_mode"
"#" = "record_macro"
"@" = "replay_macro"
"[" = ":buffer-previous"
"]" = ":buffer-next"

space.q = ":quit"
space.Q = ":quit!"
space.f = "file_picker_in_current_directory"
space.F = "goto_file"
space.b = "buffer_picker"
space."/" = "global_search"
space.y = "goto_file_start"
space.i = "goto_file_end"
space."." = "goto_last_modification"
space.c = "toggle_comments"
space.p =	"hover" ## Show documentation for item under cursor in a popup (LSP)
space.e =	"diagnostics_picker" ## Open document diagnostics picker (LSP)
space.E =	"workspace_diagnostics_picker" ## Open workspace diagnostics picker (LSP)
space.d = "goto_definition" ## Go to definition (LSP)
space.D = "goto_type_definition" ## Go to type definition (LSP)
space.s =	"symbol_picker" ## Open document symbol picker (LSP)
space.S =	"workspace_symbol_picker" ## Open workspace symbol picker (LSP)
space.r =	"rename_symbol" ## Rename symbol (LSP)
space.R =	"select_references_to_symbol_under_cursor" ## Select symbol references (LSP)
space.a =	"code_action" ## Apply code action (LSP)
# space.r = "goto_reference" ## Go to references (LSP)
# space.R = "goto_implementation" ## Go to implementation (LSP)
# space."=" = "format_selection" ## Format selection (currently nonfunctional/disabled) (LSP)
# space.g	## Debug (experimental)
# space.w	## Enter window mode
space.h.d = "goto_prev_diag"
space.h.f = "goto_prev_function"
space.h.a = "goto_prev_parameter"
space.h.t = "goto_prev_class"
space.h.c = "goto_prev_comment"
space.h.x = "goto_prev_test"
space.h.p = "goto_prev_paragraph"
space.h.s = "select_prev_sibling"
space.h.g = "goto_prev_change"
space.h.G = "goto_first_change"
space.n.d = "goto_next_diag"
space.n.f = "goto_next_function"
space.n.a = "goto_next_parameter"
space.n.t = "goto_next_class"
space.n.c = "goto_next_comment"
space.n.x = "goto_next_test"
space.n.p = "goto_next_paragraph"
space.n.s = "select_next_sibling"
space.n.g = "goto_next_change"
space.n.G = "goto_last_change"

# movement
y = "move_visual_line_up"
e = "move_char_left"
i = "move_visual_line_down"
o = "move_char_right"
Y = [ "half_page_up", "align_view_center" ]
E = "goto_first_nonwhitespace"
I = [ "half_page_down", "align_view_center" ]
O = "goto_line_end"
w	= "move_next_word_end"
W = "move_next_long_word_end"
b = "move_prev_word_start"
B = "move_prev_long_word_start"
V = "match_brackets"

# text-manipulation
c = "yank" # copy
C = ":clipboard-yank" # copy to clipboard
p = "paste_before" # paste
P = "paste_clipboard_before" # paste from clipboard
d = "delete_selection_noyank" # delete selection
D = "change_selection" # delete selection & insert 
x = "delete_selection" # cut
X = [ ":clipboard-yank", "delete_selection_noyank" ] # cut to clipboard
r = "replace" # replace character
R = "replace_with_yanked" # replace
"backspace" = [ "move_char_left", "delete_selection_noyank" ]
u = "undo"
U = "redo"
k = "copy_selection_on_next_line" # add cursor and selection below
K = "copy_selection_on_prev_line" # add cursor and selection above
"tab" =	"indent"
"S-tab"	= "unindent"
a = "open_above"
A = [ "add_newline_above", "move_visual_line_up" ]
g = "open_below"
G = [ "add_newline_below", "move_visual_line_down" ]

"+" = "surround_add"
"=" = "surround_replace"
"minus" = "surround_delete"
">" =	"switch_to_uppercase"
"~"	= "switch_case"
"<" =	"switch_to_lowercase"

# find & selection
S = "search"
M = "search_prev" # prev_match
m = "search_next" # next_match
F = "find_prev_char" # find_char_backward
f = "find_next_char" # find_char_forward
T = "till_prev_char" # till_char_backward
t = "find_till_char" # till_char_forward

N = "select_textobject_around"
H = "select_textobject_inner"
j = "join_selections_space"
J = [ "move_visual_line_up", "join_selections_space" ]
L = [ "extend_line_up", "extend_to_line_bounds" ]
l = "extend_line_below"
"%" = "select_all"
"/" = "select_regex"
"&" = [ "search_selection", "search" ]
"," = "collapse_selection"
";" = "split_selection_on_newline"
# "." = repeat_last_insert
# ":" = command_mode
"'" = "flip_selections"
"\"" = "keep_primary_selection"
"_" = "remove_primary_selection"
"(" = "rotate_selections_backward"
")" = "rotate_selections_forward"
"*" = "trim_selections"
"^" = "align_selections"

# view mode
v.t = "align_view_top"
v.c = "align_view_center"
v.b = "align_view_bottom"
v.m = "align_view_middle"

space.j = "no_op"
space."?" = "no_op"
space."'" = "no_op"
space.k = "no_op"
space.Y = "no_op"
space.P = "no_op"
"C-i" = "no_op"
"C-o" = "no_op"
"C-s" = "no_op"
"C-b" = "no_op"
"C-f" = "no_op"
"C-u" = "no_op"
"C-w" = "no_op"
# window mode
# insert mode
# picker
# prompt

[keys.select]
q = ":buffer-close"
Q = ":buffer-close!"
z = ":write"
Z = ":write!"
h = [ "collapse_selection", "insert_mode" ]
n = [ "move_char_right", "insert_mode" ]
s = "normal_mode"
"#" = "record_macro"
"@" = "replay_macro"
"[" = ":buffer-previous"
"]" = ":buffer-next"

space.q = ":quit"
space.Q = ":quit!"
space.f = "file_picker_in_current_directory"
space.F = "goto_file"
space.b = "buffer_picker"
space."/" = "global_search"
space.y = "goto_file_start"
space.i = "goto_file_end"
space."." = "goto_last_modification"
space.c = "toggle_comments"
space.p =	"hover" ## Show documentation for item under cursor in a popup (LSP)
space.e =	"diagnostics_picker" ## Open document diagnostics picker (LSP)
space.E =	"workspace_diagnostics_picker" ## Open workspace diagnostics picker (LSP)
space.d = "goto_definition" ## Go to definition (LSP)
space.D = "goto_type_definition" ## Go to type definition (LSP)
space.s =	"symbol_picker" ## Open document symbol picker (LSP)
space.S =	"workspace_symbol_picker" ## Open workspace symbol picker (LSP)
space.r =	"rename_symbol" ## Rename symbol (LSP)
space.R =	"select_references_to_symbol_under_cursor" ## Select symbol references (LSP)
space.a =	"code_action" ## Apply code action (LSP)
# space.r = "goto_reference" ## Go to references (LSP)
# space.R = "goto_implementation" ## Go to implementation (LSP)
# space."=" = "format_selection" ## Format selection (currently nonfunctional/disabled) (LSP)
# space.g	## Debug (experimental)
# space.w	## Enter window mode
space.h.d = "goto_prev_diag"
space.h.f = "goto_prev_function"
space.h.a = "goto_prev_parameter"
space.h.t = "goto_prev_class"
space.h.c = "goto_prev_comment"
space.h.x = "goto_prev_test"
space.h.p = "goto_prev_paragraph"
space.h.s = "select_prev_sibling"
space.h.g = "goto_prev_change"
space.h.G = "goto_first_change"
space.n.d = "goto_next_diag"
space.n.f = "goto_next_function"
space.n.a = "goto_next_parameter"
space.n.t = "goto_next_class"
space.n.c = "goto_next_comment"
space.n.x = "goto_next_test"
space.n.p = "goto_next_paragraph"
space.n.s = "select_next_sibling"
space.n.g = "goto_next_change"
space.n.G = "goto_last_change"

# movement
y = "extend_visual_line_up"
e = "extend_char_left"
i = "extend_visual_line_down"
o = "extend_char_right"
Y = [ "half_page_up", "align_view_center" ]
E = "goto_first_nonwhitespace"
I = [ "half_page_down", "align_view_center" ]
O = "goto_line_end"
w	= "extend_next_word_end"
W = "extend_next_long_word_end"
b = "extend_prev_word_start"
B = "extend_prev_long_word_start"
V = "match_brackets"

# text-manipulation
c = "yank" # copy
C = ":clipboard-yank" # copy to clipboard
p = "paste_before" # paste
P = "paste_clipboard_before" # paste from clipboard
d = "delete_selection_noyank" # delete selection
D = "change_selection" # delete selection & insert 
x = "delete_selection" # cut
X = [ ":clipboard-yank", "delete_selection_noyank" ] # cut to clipboard
r = "replace" # replace character
R = "replace_with_yanked" # replace
"backspace" = [ "move_char_left", "delete_selection_noyank" ]
u = "undo"
U = "redo"
k = "copy_selection_on_next_line" # add cursor and selection below
K = "copy_selection_on_prev_line" # add cursor and selection above
"tab" =	"indent"
"S-tab"	= "unindent"
a = "open_above"
A = [ "add_newline_above", "move_visual_line_up" ]
g = "open_below"
G = [ "add_newline_below", "move_visual_line_down" ]

"+" = "surround_add"
"=" = "surround_replace"
"minus" = "surround_delete"
">" =	"switch_to_uppercase"
"~"	= "switch_case"
"<" =	"switch_to_lowercase"

# find & selection
S = "search"
M = "search_prev" # prev_match
m = "search_next" # next_match
F = "find_prev_char" # find_char_backward
f = "find_next_char" # find_char_forward
T = "till_prev_char" # till_char_backward
t = "find_till_char" # till_char_forward

N = "select_textobject_around"
H = "select_textobject_inner"
j = "join_selections_space"
J = [ "move_visual_line_up", "join_selections_space" ]
L = [ "extend_line_up", "extend_to_line_bounds" ]
l = "extend_line_below"
"%" = "select_all"
"/" = "select_regex"
"&" = [ "search_selection", "search" ]
"," = "collapse_selection"
";" = "split_selection_on_newline"
# "." = repeat_last_insert
# ":" = command_mode
"'" = "flip_selections"
"\"" = "keep_primary_selection"
"_" = "remove_primary_selection"
"(" = "rotate_selections_backward"
")" = "rotate_selections_forward"
"*" = "trim_selections"
"^" = "align_selections"

# view mode
v.t = "align_view_top"
v.c = "align_view_center"
v.b = "align_view_bottom"
v.m = "align_view_middle"

space.j = "no_op"
space."?" = "no_op"
space."'" = "no_op"
space.k = "no_op"
space.Y = "no_op"
space.P = "no_op"
"C-i" = "no_op"
"C-o" = "no_op"
"C-s" = "no_op"
"C-b" = "no_op"
"C-f" = "no_op"
"C-u" = "no_op"
"C-w" = "no_op"

# "goto_last_accessed_file"
# "goto_last_modified_file"
# "goto_window_top"
# "goto_window_center"
# "goto_window_bottom"
#  = "goto_first_diag"
#  = "goto_last_diag"
#  = "decrement"
#  = "increment"
#  = "select_register"
#  = "split_selection"
# "shrink_selection"
# "expand_selection"
# "" = "jump_backward"
# "" = "jump_forward"
# "" = "save_selection"
# "rotate_selection_contents_backward"
# "rotate_selection_contents_forward"
# C-o = [":new", ":insert-output ~/.config/lf/lf-pick", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!" ]
# "earlier"
# "later"
# "goto_line_start"
# "file_picker"
# "shell_pipe" # replace output
# "shell_insert_output" # pastes new output
# "page_up"
# "page_down"
# "last_picker"
# "command_palette"
# "join_selections"
# "move_next_word_start"
# "move_next_long_word_start"
