theme = "dark_plus_mdf"
# "snazzy" "heisenberg" "mellow" "github_dark" "onedarker" "ayu_dark" "onedark"

[editor]
bufferline = "always"
line-number = "relative"
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "hidden"
  
[editor.statusline]
right = ["diagnostics", "selections", "position", "file-encoding"]

[editor.lsp]
enable = true

[keys.normal.B]
r = "surround_replace"
a = "surround_add"
d = "surround_delete"

[keys.normal]
# commands
q = ":buffer-close"
Q = ":buffer-close!"
z = ":write"
Z = ":write-quit"
"{" = ":buffer-previous"
"}" = ":buffer-next"
v = "select_mode"
V.t = "align_view_top"
V.m = "align_view_center"
V.b = "align_view_bottom"
V.T	= "goto_window_top"
V.M = "goto_window_center"
V.B	= "goto_window_bottom"
"#" = "record_macro"
"@" = "replay_macro"
# C-o = [":new", ":insert-output ~/.config/lf/lf-pick", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!" ]

# movement
w = "move_visual_line_up"
a = "move_char_left"
r = "move_visual_line_down"
s = "move_char_right"
W = "half_page_up"
A = "goto_line_start"
R = "half_page_down"
S = [ "goto_line_end", "move_char_right" ]
m = "move_prev_word_start"
M = "move_prev_long_word_start"
n = "move_next_word_start"
N = "move_next_long_word_start"
h	= "move_next_word_end"
H = "move_next_long_word_end"
C-w = "page_up"
C-a = "goto_first_nonwhitespace"
C-r = "page_down"
C-s = "goto_line_end"
b = "match_brackets"

# text-manipulation
c = "yank" # copy
C-c = ":clipboard-yank" # copy to clipboard
C = "replace" # change selection to given character
p = "paste_before" # paste
C-p = "paste_clipboard_before" # paste from clipboard
P = "replace_with_yanked" # replace
d = "delete_selection" # copy and delete
C-d = [ ":clipboard-yank", "delete_selection_noyank" ] # copy to clipboard and delete
D = "delete_selection_noyank" # delete_selection
"backspace" = [ "move_char_left", "delete_selection_noyank" ]
u = "undo"
U = "redo"
e = [ "collapse_selection", "insert_mode" ] # edit mode
E = [ "move_char_right", "insert_mode" ] # edit mode
i = "select_textobject_inner"
o = "select_textobject_around"
"ret" = [ "add_newline_below", "move_visual_line_down" ]
"S-ret" = [ "add_newline_above", "move_visual_line_up" ]
k = "copy_selection_on_next_line" # add cursor below
K = "copy_selection_on_prev_line" # add cursor above
"~"	= "switch_case"
"`" =	"switch_to_lowercase"
"C-`" =	"switch_to_uppercase"
"tab" =	"indent"
"S-tab"	= "unindent"
"|" = "shell_pipe" # replace output
"\\" = "shell_insert_output" # pastes new output

# find & selection
"/" = "search"
"&" = "select_regex"
"C-/" = [ "search_selection", "search" ]
"C-&" = "split_selection"
"[" = "search_prev"
"]" = "search_next"
f = "find_next_char" # find_next_char
F = "find_prev_char" # find_prev_char
t = "find_till_char" # till_next_char
T = "till_prev_char" # till_prev_char
j = "join_selections"
J = "join_selections_space"
l = "extend_line_below"
L = "extend_line_up"
C-l = "select_all"
"'" = "flip_selections" # toggle selection cursor
"." = "collapse_selection"
"," = "keep_primary_selection" # collapse multiple cursors
";" = "split_selection_on_newline"
"minus" = "align_selections"
"_" = "trim_selections"

"(" = { d = "goto_prev_diag", D = "goto_first_diag", f = "goto_prev_function", c = "goto_prev_comment", a = "goto_prev_parameter", t = "goto_prev_class", s = "select_prev_sibling", T = "goto_prev_test", g = "goto_prev_change", G = "goto_first_change", "[" = "shrink_selection", y = "open_above", l = "goto_file_start", "(" = "goto_prev_paragraph" }
")" = { d = "goto_next_diag", D = "goto_last_diag",  f = "goto_next_function", c = "goto_next_comment", a = "goto_next_parameter", t = "goto_next_class", s = "select_next_sibling", T = "goto_next_test", g = "goto_next_change", G = "goto_last_change",  "]" = "expand_selection", y = "open_below", l = "goto_last_line" , ")" = "goto_prev_paragraph" }

[keys.normal."g"]
space.c = "toggle_comments"

# d	"goto_definition"
# y	"goto_type_definition"
# r	"goto_reference"
# i	"goto_implementation"
# a	"goto_last_accessed_file"
# m	"goto_last_modified_file"
# .	"goto_last_modification"
# "remove_primary_selection"

[keys.select]
# commands
q = ":buffer-close"
Q = ":buffer-close!"
z = ":write"
Z = ":write-quit"
"{" = ":buffer-previous"
"}" = ":buffer-next"
v = "normal_mode"
V.t = "align_view_top"
V.m = "align_view_center"
V.b = "align_view_bottom"
V.T	= "goto_window_top"
V.M = "goto_window_center"
V.B	= "goto_window_bottom"
"#" = "record_macro"
"@" = "replay_macro"

# find & selection
"/" = "search"
"&" = "select_regex"
"C-/" = [ "search_selection", "search" ]
"C-&" = "split_selection"
"[" = "search_prev"
"]" = "search_next"
f = "find_next_char" # find_next_char
F = "find_prev_char" # find_prev_char
t = "find_till_char" # till_next_char
T = "till_prev_char" # till_prev_char
j = "join_selections"
J = "join_selections_space"
l = "extend_line_below"
L = "extend_line_up"
C-l = "select_all"
"'" = "flip_selections" # toggle selection cursor
"." = "collapse_selection"
"," = "keep_primary_selection" # collapse multiple cursors
";" = "split_selection_on_newline"
"minus" = "align_selections"
"_" = "trim_selections"

# movement
w = "extend_visual_line_up"
a = "extend_char_left"
r = "extend_visual_line_down"
s = "extend_char_right"
W = "half_page_up"
A = "goto_line_start"
R = "half_page_down"
S = [ "goto_line_end", "extend_char_right" ]
m = "extend_prev_word_start"
M = "extend_prev_long_word_start"
n = "extend_next_word_start"
N = "extend_next_long_word_start"
h	= "extend_next_word_end"
H = "extend_next_long_word_end"
C-w = "page_up"
C-a = "goto_first_nonwhitespace"
C-r = "page_down"
C-s = "goto_line_end"
b = "match_brackets"

# text-manipulation
c = "yank" # copy
C-c = ":clipboard-yank" # copy to clipboard
C = "replace" # change selection to given character
p = "paste_before" # paste
C-p = "paste_clipboard_before" # paste from clipboard
P = "replace_with_yanked" # replace
d = "delete_selection" # copy and delete
C-d = [ ":clipboard-yank", "delete_selection_noyank" ] # copy to clipboard and delete
D = "delete_selection_noyank" # delete_selection
"backspace" = [ "move_char_left", "delete_selection_noyank" ]
u = "undo"
U = "redo"
e = [ "collapse_selection", "insert_mode" ] # edit mode
E = [ "move_char_right", "insert_mode" ] # edit mode
i = "select_textobject_inner"
o = "select_textobject_around"
"ret" = [ "add_newline_below", "move_visual_line_down" ]
"S-ret" = [ "add_newline_above", "move_visual_line_up" ]
k = "copy_selection_on_next_line" # add cursor below
K = "copy_selection_on_prev_line" # add cursor above
"~"	= "switch_case"
"`" =	"switch_to_lowercase"
"C-`" =	"switch_to_uppercase"
"tab" =	"indent"
"S-tab"	= "unindent"
"|" = "shell_pipe" # replace output
"\\" = "shell_insert_output" # pastes new output
